apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - {{ .Values.volume.accessMode }}
  {{- if .Values.volume.storageClassName }}
  storageClassName: {{ .Values.volume.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.volume.size }}
