apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.ports.meta }}
      targetPort: {{ .Values.ports.meta }}
      protocol: TCP
      name: meta
    - port: {{ .Values.ports.api }}
      targetPort: {{ .Values.ports.api }}
      protocol: TCP
      name: api
    - port: {{ .Values.ports.client }}
      targetPort: {{ .Values.ports.client }}
      protocol: TCP
      name: client
  selector:
    app: {{ .Chart.Name }}
